### ISSUE TITLE
Adds new items to S3, but doesn't update the DB

### ISSUE THREAD

**Issue by acourter27** [kanboard/plugin-s3#15]
Note that I'm running kanboard in a docker instance. When I ran it inside a /www/ folder, this issue didn't exist.

Docker compose script is pretty plain:
```
version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    restart: always
    ports:
      - "8005:80"
      - "4435:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
```

The instance sits behind a Nginx Reverse Proxy (using Nginx Proxy Manager).
Nginx configuration
```
# ------------------------------------------------------------
# kanboard.[domain]
# ------------------------------------------------------------


server {
  set $forward_scheme http;
  set $server         "[Public IP address of server]";
  set $port           8005;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;


  server_name kanboard.[domain];


  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-14/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-14/privkey.pem;


    # Force SSL
    include conf.d/include/force-ssl.conf;


  access_log /data/logs/proxy-host-11_access.log proxy;
  error_log /data/logs/proxy-host-11_error.log warn;

  location / {
    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```
### Actual behaviour
When I look at S3, I can confirm that the file was uploaded properly. But, the task itself doesn't refresh to show the item, so I can't retrieve it or even see it. When I first migrated from /www/ to docker I could see the old items that had been uploaded, and I could download them, but nothing new can be added.

I'm assuming it's not updating the DB, I don't know this for sure.

### Expected behaviour
When an item is added to S3, it should be seen on the task page so it can be retrieved.

### Steps to reproduce
Create new task
Upload document

### Configuration

    Plugin version: 1.0.5
    Application version: v1.2.22
    PHP version: 8.0.14
    PHP SAPI: fpm-fcgi
    HTTP Client: cURL
    OS version: Linux 5.13.0-1023-aws
    Database driver: sqlite
    Database version: 3.36.0
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0
